version: '3'
services:
  strapi:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        STRAPI_VERSION: 3.1.6
        BASE_VERSION: 12-alpine
    #image: strapi/strapi
    #image: strapi/base
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
      - '8000:8000'
    depends_on:
      - postgres
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    volumes:
      - ./front-end:/var/build
      - ./front-end/assets:/var/build/assets
      - /var/build/node_modules
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
